import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        outline: '#8b7263',
        'secondary-fixed-dim': '#bac8dc',
        'surface-dim': '#d9dadb',
        'outline-variant': '#dec1af',
        'secondary-container': '#d3e1f6',
        'on-background': '#191c1d',
        'surface-container-high': '#e7e8e9',
        'on-primary-container': '#572800',
        'surface-container': '#edeeef',
        'primary-container': '#f57c00',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'surface-tint': '#964900',
        'on-tertiary-fixed-variant': '#005312',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#566475',
        'inverse-surface': '#2e3132',
        surface: '#f8f9fa',
        'primary-fixed-dim': '#ffb786',
        'tertiary-fixed-dim': '#88d982',
        primary: '#964900',
        'on-secondary-fixed': '#0f1c2c',
        'on-primary-fixed-variant': '#723600',
        tertiary: '#1b6d24',
        'on-error': '#ffffff',
        'primary-fixed': '#ffdcc6',
        'secondary-fixed': '#d6e4f9',
        'surface-container-low': '#f3f4f5',
        'on-primary': '#ffffff',
        'inverse-primary': '#ffb786',
        'on-surface': '#191c1d',
        'on-secondary-fixed-variant': '#3a4859',
        'on-primary-fixed': '#311300',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-highest': '#e1e3e4',
        background: '#f8f9fa',
        'tertiary-container': '#5faf5d',
        'error-container': '#ffdad6',
        'surface-variant': '#e1e3e4',
        secondary: '#525f71',
        'tertiary-fixed': '#a3f69c',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#574235',
        'on-tertiary-container': '#003f0b',
      },
      fontFamily: {
        headline: 'var(--font-headline)',
        body: 'var(--font-body)',
      },
    },
  },
  plugins: [],
};

export default config;
